const { inputIsValid } = require("../../src/modules/calculator.js");

describe("inputIsValid", () => {
  test.each([
    { letter: "x", expected: true },
    { letter: "X", expected: true },
    { letter: "a", expected: false },
    { letter: "A", expected: false },
    { letter: "b", expected: false },
    { letter: "B", expected: false },
    { letter: "c", expected: false },
    { letter: "C", expected: false },
    { letter: "d", expected: false },
    { letter: "D", expected: false },
    { letter: "e", expected: false },
    { letter: "E", expected: false },
    { letter: "f", expected: false },
    { letter: "F", expected: false },
    { letter: "g", expected: false },
    { letter: "G", expected: false },
    { letter: "h", expected: false },
    { letter: "H", expected: false },
    { letter: "i", expected: false },
    { letter: "I", expected: false },
    { letter: "j", expected: false },
    { letter: "J", expected: false },
    { letter: "k", expected: false },
    { letter: "K", expected: false },
    { letter: "l", expected: false },
    { letter: "L", expected: false },
    { letter: "m", expected: false },
    { letter: "M", expected: false },
    { letter: "n", expected: false },
    { letter: "N", expected: false },
    { letter: "o", expected: false },
    { letter: "O", expected: false },
    { letter: "p", expected: false },
    { letter: "P", expected: false },
    { letter: "q", expected: false },
    { letter: "Q", expected: false },
    { letter: "r", expected: false },
    { letter: "R", expected: false },
    { letter: "s", expected: false },
    { letter: "S", expected: false },
    { letter: "t", expected: false },
    { letter: "T", expected: false },
    { letter: "u", expected: false },
    { letter: "U", expected: false },
    { letter: "v", expected: false },
    { letter: "V", expected: false },
    { letter: "w", expected: false },
    { letter: "W", expected: false },
    { letter: "y", expected: false },
    { letter: "Y", expected: false },
    { letter: "z", expected: false },
    { letter: "Z", expected: false },
  ])("$letter should return $expected", ({ letter, expected }) => {
    expect(inputIsValid(letter)).toBe(expected);
  });

  test.each([
    { symbol: "%", expected: true },
    { symbol: "-", expected: true },
    { symbol: "+", expected: true },
    { symbol: "/", expected: true },
    { symbol: "*", expected: true },
    { symbol: ".", expected: true },
    { symbol: "(", expected: true },
    { symbol: ")", expected: true },
    { symbol: "`", expected: false },
    { symbol: "¬", expected: false },
    { symbol: "!", expected: false },
    { symbol: `"`, expected: false },
    { symbol: "£", expected: false },
    { symbol: "$", expected: false },
    { symbol: "^", expected: false },
    { symbol: "&", expected: false },
    { symbol: "_", expected: false },
    { symbol: "[", expected: false },
    { symbol: "]", expected: false },
    { symbol: "{", expected: false },
    { symbol: "}", expected: false },
    { symbol: ";", expected: false },
    { symbol: ":", expected: false },
    { symbol: "'", expected: false },
    { symbol: "@", expected: false },
    { symbol: "#", expected: false },
    { symbol: "~", expected: false },
    { symbol: "<", expected: false },
    { symbol: ">", expected: false },
    { symbol: "?", expected: false },
    { symbol: "=", expected: false },
    { symbol: "\\", expected: false },
  ])("$symbol should return $expected", ({ symbol, expected }) => {
    expect(inputIsValid(symbol)).toBe(expected);
  });
});
